import { PromptParameters } from './types';

export const initialParameters: PromptParameters = {
  shotType: 'medium-shot',
  cameraAngle: 'eye-level',
  cameraMovement: 'none',
  lens: '35mm',
  composition: 'rule-of-thirds',
  lighting: 'cinematic',
  style: 'photorealistic',
  filmQuality: '4k',
  pacing: 'normal',
  timeOfDay: 'day',
  location: 'unspecified',
  depthOfField: 'natural',
  texture: 'standard-definition',
  colorPalette: 'vibrant',
  genre: 'drama',
};

export const ASPECT_RATIO_OPTIONS = [
    { value: '16:9', labelKey: 'aspectRatio.widescreen' },
    { value: '9:16', labelKey: 'aspectRatio.vertical' },
    { value: '1:1', labelKey: 'aspectRatio.square' },
    { value: '4:3', labelKey: 'aspectRatio.classic' },
    { value: '2.39:1', labelKey: 'aspectRatio.cinemascope' },
];

export const PROMPT_OPTIONS = {
  genre: [
    { value: 'drama', labelKey: 'genre.drama' },
    { value: 'action', labelKey: 'genre.action' },
    { value: 'comedy', labelKey: 'genre.comedy' },
    { value: 'sci-fi', labelKey: 'genre.sciFi' },
    { value: 'horror', labelKey: 'genre.horror' },
    { value: 'fantasy', labelKey: 'genre.fantasy' },
    { value: 'documentary', labelKey: 'genre.documentary' },
    { value: 'thriller', labelKey: 'genre.thriller' },
  ],
  shotType: [
    { value: 'extreme-close-up', labelKey: 'shotType.extremeCloseUp' },
    { value: 'close-up', labelKey: 'shotType.closeUp' },
    { value: 'medium-shot', labelKey: 'shotType.mediumShot' },
    { value: 'long-shot', labelKey: 'shotType.longShot' },
    { value: 'establishing-shot', labelKey: 'shotType.establishingShot' },
    { value: 'pov', labelKey: 'shotType.pov' },
  ],
  cameraAngle: [
    { value: 'eye-level', labelKey: 'cameraAngle.eyeLevel' },
    { value: 'high-angle', labelKey: 'cameraAngle.highAngle' },
    { value: 'low-angle', labelKey: 'cameraAngle.lowAngle' },
    { value: 'dutch-angle', labelKey: 'cameraAngle.dutchAngle' },
    { value: 'birds-eye-view', labelKey: 'cameraAngle.birdsEyeView' },
  ],
  cameraMovement: [
    { value: 'none', labelKey: 'cameraMovement.none' },
    { value: 'pan', labelKey: 'cameraMovement.pan' },
    { value: 'tilt', labelKey: 'cameraMovement.tilt' },
    { value: 'dolly-zoom', labelKey: 'cameraMovement.dollyZoom' },
    { value: 'crane-shot', labelKey: 'cameraMovement.craneShot' },
    { value: 'handheld', labelKey: 'cameraMovement.handheld' },
    { value: 'drone-shot', labelKey: 'cameraMovement.droneShot' },
    { value: 'gimbal', labelKey: 'cameraMovement.gimbal' },
  ],
   lens: [
    { value: '24mm', labelKey: 'lens.24' },
    { value: '35mm', labelKey: 'lens.35' },
    { value: '50mm', labelKey: 'lens.50' },
    { value: '85mm', labelKey: 'lens.85' },
    { value: '135mm', labelKey: 'lens.135' },
  ],
  composition: [
    { value: 'rule-of-thirds', labelKey: 'composition.ruleOfThirds' },
    { value: 'leading-lines', labelKey: 'composition.leadingLines' },
    { value: 'centered', labelKey: 'composition.centered' },
    { value: 'symmetry', labelKey: 'composition.symmetry' },
    { value: 'frame-within-frame', labelKey: 'composition.frameWithinFrame' },
  ],
  lighting: [
    { value: 'cinematic', labelKey: 'lighting.cinematic' },
    { value: 'golden-hour', labelKey: 'lighting.goldenHour' },
    { value: 'blue-hour', labelKey: 'lighting.blueHour' },
    { value: 'high-key', labelKey: 'lighting.highKey' },
    { value: 'low-key', labelKey: 'lighting.lowKey' },
    { value: 'neon', labelKey: 'lighting.neon' },
    { value: 'backlight', labelKey: 'lighting.backlight' },
    { value: 'studio-lighting', labelKey: 'lighting.studio' },
  ],
  style: [
    { value: 'photorealistic', labelKey: 'style.photorealistic' },
    { value: 'cinematic-film', labelKey: 'style.cinematicFilm' },
    { value: 'cinematography-like-denis-villeneuve', labelKey: 'style.denisVilleneuve' },
    { value: 'style-of-wes-anderson', labelKey: 'style.wesAnderson' },
    { value: 'style-of-quentin-tarantino', labelKey: 'style.quentinTarantino' },
    { value: 'anime', labelKey: 'style.anime' },
    { value: 'documentary', labelKey: 'style.documentary' },
    { value: 'found-footage', labelKey: 'style.foundFootage' },
    { value: '3d-render', labelKey: 'style.threeDRender' },
    { value: 'macro-photography', labelKey: 'style.macroPhotography' },
    { value: 'fantasy-art', labelKey: 'style.fantasyArt' },
    { value: 'vaporwave', labelKey: 'style.vaporwave' },
  ],
  filmQuality: [
    { value: '4k', labelKey: 'filmQuality.fourK' },
    { value: '8k', labelKey: 'filmQuality.eightK' },
    { value: '35mm-film', labelKey: 'filmQuality.thirtyFiveMM' },
    { value: '16mm-film', labelKey: 'filmQuality.sixteenMM' },
    { value: 'vhs', labelKey: 'filmQuality.vhs' },
    { value: 'imax', labelKey: 'filmQuality.imax' },
  ],
  pacing: [
    { value: 'normal', labelKey: 'pacing.normal' },
    { value: 'slow-motion', labelKey: 'pacing.slowMotion' },
    { value: 'fast-motion', labelKey: 'pacing.fastMotion' },
    { value: 'time-lapse', labelKey: 'pacing.timeLapse' },
  ],
  timeOfDay: [
    { value: 'day', labelKey: 'timeOfDay.daytime' },
    { value: 'night', labelKey: 'timeOfDay.nighttime' },
    { value: 'dawn', labelKey: 'timeOfDay.dawn' },
    { value: 'dusk', labelKey: 'timeOfDay.dusk' },
    { value: 'midnight', labelKey: 'timeOfDay.midnight' },
  ],
  location: [
    { value: 'unspecified', labelKey: 'location.unspecified' },
    { value: 'cityscape', labelKey: 'location.cityscape' },
    { value: 'forest', labelKey: 'location.forest' },
    { value: 'ocean', labelKey: 'location.ocean' },
    { value: 'mountains', labelKey: 'location.mountains' },
    { value: 'desert', labelKey: 'location.desert' },
    { value: 'sci-fi-interior', labelKey: 'location.sciFiInterior' },
  ],
  depthOfField: [
    { value: 'natural', labelKey: 'depthOfField.natural' },
    { value: 'shallow', labelKey: 'depthOfField.shallow' },
    { value: 'deep', labelKey: 'depthOfField.deep' },
    { value: 'rack-focus', labelKey: 'depthOfField.rackFocus' },
  ],
  texture: [
    { value: 'standard-definition', labelKey: 'texture.standard' },
    { value: 'smooth-glossy', labelKey: 'texture.smooth' },
    { value: 'rough-matte', labelKey: 'texture.rough' },
    { value: 'heavy-film-grain', labelKey: 'texture.heavyGrain' },
    { value: 'sharp-and-clean', labelKey: 'texture.sharp' },
  ],
  colorPalette: [
    { value: 'vibrant', labelKey: 'colorPalette.vibrant' },
    { value: 'muted', labelKey: 'colorPalette.muted' },
    { value: 'monochromatic', labelKey: 'colorPalette.monochromatic' },
    { value: 'pastel', labelKey: 'colorPalette.pastel' },
    { value: 'neon-synthwave', labelKey: 'colorPalette.neon' },
    { value: 'warm-tones', labelKey: 'colorPalette.warm' },
    { value: 'cool-tones', labelKey: 'colorPalette.cool' },
  ]
};
